#!/bin/bash
# Upload nginx config template to GCS for native hydrogen deployments.
# Run this once.

set -e

BUCKET="gs://puru-releases"

cat > puru-hydrogen.conf << 'NGINX'
# Puru Hydrogen — Nginx config for native JAR deployments
# Serves the Angular build from /opt/puru/nginx/html/
# Generated by puru-nucleus

server {
    listen 80;
    server_name _;

    root /opt/puru/nginx/html;
    index index.html;

    # Angular SPA — route all non-file requests to index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy API requests to backend services
    location /api/auth/ {
        proxy_pass http://127.0.0.1:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/xenon/ {
        proxy_pass http://127.0.0.1:8081/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /has/ {
        proxy_pass http://127.0.0.1:8082/has/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /pacs/ {
        proxy_pass http://127.0.0.1:8083/pacs/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/comm/ {
        proxy_pass http://127.0.0.1:8085/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /ws/ {
        proxy_pass http://127.0.0.1:8086/ws/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }

    # Static assets — cache aggressively
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2?)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # gzip
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;
    gzip_min_length 1000;
}
NGINX

echo "Uploading nginx config template..."
gsutil cp puru-hydrogen.conf "$BUCKET/templates/nginx/puru-hydrogen.conf"

echo "Done! Template uploaded to $BUCKET/templates/nginx/puru-hydrogen.conf"
rm puru-hydrogen.conf
